version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runad: ec2-user