name: Build & Deploy
env:
  PROJECT_NAME: Express-app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: delete package-lock.json
        run: rm package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Create env file
        run: |	
          touch .env	

      - name: Make tar file
        run: tar -cpvzf ./$GITHUB_SHA.tgz *
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./$GITHUB_SHA.tgz s3://express-app-s3/$PROJECT_NAME/$GITHUB_SHA.tgz

      - name: Code Deploy
        run: aws deploy create-deployment --application-name Express-app --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name express-app --s3-location bucket=express-app-s3,bundleType=tgz,key=$PROJECT_NAME/$GITHUB_SHA.tgz
